name: Greetings

on: [pull_request_target, issues, push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # This condition ensures the message is only displayed on the first push
        # to the repository (not subsequent pushes)
        issue-message: ${{ github.event.type == 'push' && github.event.commits[0].message.contains('first contribution') ? 'Welcome! This is your first contribution to this repository.' : '' }}
